Legend callback
antvis/component pull request #227
Opened 2021-05-28 05:03 UTC by Aarebecca

##### Checklist

- [ ] `npm test` passes
- [ ] tests and/or benchmarks are included
- [ ] commit message follows commit guidelines

##### Description of change

- 使用`\\TODO`注释了单元测试中不通过的部分
- Legend 添加了Marker.symbol, Marker.style, itemName, itemValue 的回调函数

2021-05-28 05:23 UTC, visiky requested changes

2021-05-28 05:23 UTC, visiky commented on package.json
> +    "test-live": "DEBUG_MODE=1 jest --watch",
还是少了？

2021-05-28 05:23 UTC, visiky commented on src/legend/category.ts
>        const markerShape = this.drawMarker(subGroup, marker, item, itemHeight);
建议改成：
```ts
let markerCfg = marker;
if (isFunction(markerCfg)) {
   markerCfg = markerCfg.apply(....)
}
const markerShape = this.drawMarker(subGroup, markerCfg, item, itemHeight);
```

2021-05-28 05:23 UTC, visiky commented on src/types.ts
> +  style?: ShapeAttrs | ShapeAttrsCallback;
对应类型定义：
```ts
type LegendMarkerCfgCallBack = (....) => LegendMarkerCfg;
{
     marker?: LegendMarkerCfg | LegendMarkerCfgCallBack;
}
```

2021-06-02 14:06 UTC, visiky commented
marker callback: https://github.com/antvis/G2/pull/3448

2021-06-02 15:48 UTC, Aarebecca commented on package.json
> +    "test-live": "DEBUG_MODE=1 jest --watch",
已经回退版本，重新更改了

2021-06-03 03:59 UTC, visiky commented
需求背景: https://github.com/antvis/G2Plot/issues/2558

2021-06-03 04:01 UTC, visiky approved these changes

2021-06-03 04:59 UTC, merged