feat(axis):添加坐标轴标题详细说明icon按钮
antvis/component pull request #270
Opened 2022-04-11 08:06 UTC by zhangjunjie-loki

##### Checklist
- [x] `npm test` passes
- [x] tests and/or benchmarks are included
- [x] commit message follows commit guidelines

##### Description of change
1. 添加了坐标轴标题详细说明 icon 按钮
2. 添加了点击热区，icon 上层添加透明矩形。

<img width="512" alt="Snipaste_2022-04-11_16-03-44" src="https://user-images.githubusercontent.com/95538236/162692056-632f4676-a427-4488-919b-aed3d7b29244.png">

2022-04-11 08:35 UTC, visiky requested changes

2022-04-11 08:35 UTC, visiky commented on src/axis/base.ts
> +    if(this.get('title').description !== '') {
`this.get('title')?.description` 判空，title 可能为空

2022-04-11 08:35 UTC, visiky commented on src/axis/base.ts
> +    console.log('u1134');
log 删除

2022-04-11 08:35 UTC, visiky commented on src/axis/base.ts
> +      fillOpacity: .25,
样式运行外部配置，考虑暗色场景

2022-04-11 08:43 UTC, visiky commented
建议: description 存储在一个 axis-description 的 group 内，方便上层直接监听 axis-description 的事件

```ts
const descGroup = group.addGroup({ name: 'axis-description' });

descGroup.addShape('path', { name: 'axis-description-icon', attrs: { ... } });

descGroup.on('mouseenter', () => {
  // do something
});
```

2022-04-11 11:56 UTC, zhangjunjie-loki commented
已全部修改。title 配置中新增 iconStyle 字段

2022-04-12 01:52 UTC, visiky approved these changes

2022-04-12 01:53 UTC, merged