fix(category):分页图例，分页宽度获取错误，导致部分图例被剪切
antvis/component pull request #288
Opened 2023-02-08 02:57 UTC by ai-qing-hai

- [ ] 错误

![image](https://user-images.githubusercontent.com/65594180/217417290-1a2c53c5-c18c-42ef-9724-c2c5276d0fd5.png)

- [x] 正常显示

![image](https://user-images.githubusercontent.com/65594180/217417053-d267cbd9-9ab6-4bba-a927-f95ec7e874ca.png)

2023-02-08 03:47 UTC, visiky requested changes
还有两个建议：
1、增加一个单测～
2、PR 描述，形容对比的时候，可以用表格

|Before|After|
|---|---|
| ![]() | ![]() | 

<img width="120" alt="image" src="https://user-images.githubusercontent.com/15646325/217426729-171c7601-c0b4-4dc0-9e40-d5212deb0f2a.png">

2023-02-08 03:48 UTC, visiky commented on src/legend/category.ts
> +              x: navigationX,
- 理论上，`navigationX` 代表分页器的 x 坐标，在同一坐标系下等价于  `navigationBBox.minX` 
- 不出意外的话，`navigationBBox.minX` 一直都是 0？（这里是吗？）

问题分析：
- 这里的条件是：horizontal 布局，然后在指定条件（这里的 if 条件）下判断是否需要换行了，然后设置 page+=1。同时，根据第一页（pages ===1 ） 的情况来计算 pageWidth。
- 这里根据 legend-item 的位置来计算，确实会有问题。另外 `widthLimit` 应该没什么作用，指定条件判断是否需要换行，应该不太需要 `widthLimit` 

这里太多 mutable 了，我们稍微根据逻辑优化拆解下：
```ts
/**  判断当前 item 是否溢出当前页。是的话，需要换行 */
function shouldWrap(item, currentPoint) {
  const bbox = item.getBBox();
  const width = itemWidth || bbox.width;
  const newItemXPos = currentPoint.x + width + itemSpacing + navigationBBox.width;
  return newItemXPos > maxWidth;
}

if (layout === 'horizontal') {
  const maxRow = this.get('maxRow') || 1;
  const maxRowHeight = itemHeight + (maxRow === 1 ? 0 : itemMarginBottom);
  // 分页器一直靠右上角
  const navigationX = maxWidth - itemSpacing - navigationBBox.width - navigationBBox.minX; // 理论上不需要减 navigationBBox.minX
  this.pageHeight = maxRowHeight * maxRow;
  this.pageWidth = navigationX;

  each(subGroups, (item) => {
    const bbox = item.getBBox();
    const width = itemWidth || bbox.width;
    if (shouldWrap(item, currentPoint)) {
      if (pages === 1) {
        this.moveElementTo(navigation, {
          x: navigationX,
          y: currentPoint.y + itemHeight / 2 - navigationBBox.height / 2 - navigationBBox.minY,
        });
      }
      pages += 1;
      currentPoint.x = startX;
      currentPoint.y += maxRowHeight;
    }
    this.moveElementTo(item, currentPoint);
    item.getParent().setClip({
      type: 'rect',
      attrs: {
        x: currentPoint.x,
        y: currentPoint.y,
        width: width + itemSpacing,
        height: itemHeight,
      },
    });
    currentPoint.x += width + itemSpacing;
  });
}
```

2023-02-08 06:29 UTC, ai-qing-hai commented on src/legend/category.ts
> +              x: navigationX,
对的 navigationBBox.minX 这里是 0 。

2023-02-08 08:40 UTC, ai-qing-hai commented on src/legend/category.ts
> +              x: navigationX,
widthLimit 我觉的得保留。  
![image](https://user-images.githubusercontent.com/65594180/217478054-6a75e60a-bfb1-49d1-b006-b680c80fc139.png)
这部分逻辑依然会影响 单测 。 如果删除会影响 legend 的显示。 尽量先保留原了的逻辑

2023-02-09 02:59 UTC, visiky commented on tests/unit/legend/category-flippage-spec.ts
> +      expect(itemGroup.getParent().getClip().getBBox().width).toBeCloseTo(113.2);
建议这里改成 toBeGreaterThan(100) 就好，修复之前应该是第一个图例项 `11111` 的宽度左右。这里断言大于 100 就行了，因为宽度测算在不同平台下可能有误差，toBeCloseTo 还是不太准确

2023-02-09 06:01 UTC, ai-qing-hai commented on tests/unit/legend/category-flippage-spec.ts
> +      expect(itemGroup.getParent().getClip().getBBox().width).toBeCloseTo(113.2);
修改完成

2023-02-09 06:17 UTC, merged