Feat: add more datamarker annotation direction
antvis/component pull request #298
Opened 2023-03-31 03:42 UTC by sersishen

##### 变更描述
希望可以在0.8.x版本里 让dataMarker类型标注功能支持更多的朝向

- dataMarker类型标注功能支持更多的朝向：'leftward' | 'rightward'
- 对dataMarker类型标注的自动布局进行了优化

![image](https://user-images.githubusercontent.com/68099359/228777365-338c90c3-c7e0-449e-8482-5b12f29dd222.png)

![image](https://user-images.githubusercontent.com/68099359/228777907-c4bb6bef-957b-42c7-9a98-bf679cf5ab3c.png)

2023-03-31 08:11 UTC, pepper-nice reviewed
加个单测吧

2023-03-31 09:20 UTC, pearmini requested changes
加一个单测就好啦 👍

2023-04-03 06:56 UTC, sersishen commented
单测已添加🙆

2023-04-03 06:57 UTC, pearmini approved these changes
🚀🚀🚀

2023-04-03 07:01 UTC, merged