Fix: change the scrollbar, legend hover style to the `cursor: pointer`
antvis/component pull request #313
Opened 2023-11-14 02:16 UTC by Runtus

- [x] change the scrollbar, legend hover style to the `cursor: pointer` when draggable.
- [x] run `npm run test` 

* before 
<img width="375" alt="image" src="https://github.com/antvis/component/assets/48038769/b8879825-6a57-468a-bf6b-eb4d071d9296">
<img width="515" alt="image" src="https://github.com/antvis/component/assets/48038769/972d0d8e-09bb-4e44-a891-f42555896543">

* after
<img width="333" alt="image" src="https://github.com/antvis/component/assets/48038769/5d5207fe-eb81-459c-8b56-a4084474ab5b">
<img width="473" alt="image" src="https://github.com/antvis/component/assets/48038769/898a15be-c703-434d-ab68-8c2bcdc90901">
 
* the issue: [legend、slider、scrollbar 涉及到鼠标拖拽的，都需要设置鼠标样式为手型 ](https://github.com/antvis/G2/issues/5791)

2023-11-23 08:00 UTC, pearmini requested changes
更新一下 PR 的描述，加几张动图？我看看实际的效果。

2023-11-23 08:33 UTC, Runtus commented
* 这是scrollbar的演示动图
![scroll](https://github.com/antvis/component/assets/48038769/a14b02da-f8cf-46fe-914a-f1c1e38750d5)
* 这shi是legend的演示动图
![legend](https://github.com/antvis/component/assets/48038769/77b18722-4ed0-46c9-8785-e5e6564f59a4)

2023-11-23 09:46 UTC, pearmini requested changes
OK，看上去很细节！升级一下 `package.json` 的 version 字段到 `1.0.0`，然后我发一个版本。

2023-11-24 01:53 UTC, hustcc commented on src/ui/legend/continuous.ts
> +    this.addEventListener('pointerover', this.changeCursor('pointer'));
这里是不是不用 pointerover，直接设置 this.style.cursor = 'pointer'; 就可以了，因为这个样式，就是在鼠标 hover 的时候，才显示。

2023-11-24 04:20 UTC, Runtus commented on src/ui/legend/continuous.ts
> +    this.addEventListener('pointerover', this.changeCursor('pointer'));
刚刚我再次梳理了下逻辑，这个地方确实直接用`this.style.cursor = 'pointer'`更好，因为该函数是组件初始化的时候会执行的，所以只需要保证第一次指针指到组件的时候是`cursor: pointer`样式就行，而不需要绑定一个事件去重复设置`cursor: pointer`。
我这马上改一下。

2023-11-29 02:21 UTC, pearmini approved these changes

2023-11-29 03:00 UTC, merged